# Generated by cpp11: do not edit by hand

c_bigfloat <- function(x) {
  .Call(`_bignum_c_bigfloat`, x)
}

c_bigfloat_to_logical <- function(x) {
  .Call(`_bignum_c_bigfloat_to_logical`, x)
}

c_bigfloat_to_integer <- function(x) {
  .Call(`_bignum_c_bigfloat_to_integer`, x)
}

c_bigfloat_to_double <- function(x) {
  .Call(`_bignum_c_bigfloat_to_double`, x)
}

c_bigfloat_format <- function(x, notation, digits, is_sigfig) {
  .Call(`_bignum_c_bigfloat_format`, x, notation, digits, is_sigfig)
}

c_bigfloat_compare <- function(lhs, rhs, na_equal) {
  .Call(`_bignum_c_bigfloat_compare`, lhs, rhs, na_equal)
}

c_bigfloat_rank <- function(x) {
  .Call(`_bignum_c_bigfloat_rank`, x)
}

c_bigfloat_add <- function(lhs, rhs) {
  .Call(`_bignum_c_bigfloat_add`, lhs, rhs)
}

c_bigfloat_subtract <- function(lhs, rhs) {
  .Call(`_bignum_c_bigfloat_subtract`, lhs, rhs)
}

c_bigfloat_multiply <- function(lhs, rhs) {
  .Call(`_bignum_c_bigfloat_multiply`, lhs, rhs)
}

c_bigfloat_divide <- function(lhs, rhs) {
  .Call(`_bignum_c_bigfloat_divide`, lhs, rhs)
}

c_bigfloat_pow <- function(lhs, rhs) {
  .Call(`_bignum_c_bigfloat_pow`, lhs, rhs)
}

c_bigfloat_modulo <- function(lhs, rhs) {
  .Call(`_bignum_c_bigfloat_modulo`, lhs, rhs)
}

c_bigfloat_sum <- function(x, na_rm) {
  .Call(`_bignum_c_bigfloat_sum`, x, na_rm)
}

c_bigfloat_prod <- function(x, na_rm) {
  .Call(`_bignum_c_bigfloat_prod`, x, na_rm)
}

c_bigfloat_cumsum <- function(x) {
  .Call(`_bignum_c_bigfloat_cumsum`, x)
}

c_bigfloat_cumprod <- function(x) {
  .Call(`_bignum_c_bigfloat_cumprod`, x)
}

c_bigfloat_cummax <- function(x) {
  .Call(`_bignum_c_bigfloat_cummax`, x)
}

c_bigfloat_cummin <- function(x) {
  .Call(`_bignum_c_bigfloat_cummin`, x)
}

c_bigfloat_abs <- function(lhs) {
  .Call(`_bignum_c_bigfloat_abs`, lhs)
}

c_bigfloat_sign <- function(lhs) {
  .Call(`_bignum_c_bigfloat_sign`, lhs)
}

c_bigfloat_sqrt <- function(lhs) {
  .Call(`_bignum_c_bigfloat_sqrt`, lhs)
}

c_bigfloat_ceiling <- function(lhs) {
  .Call(`_bignum_c_bigfloat_ceiling`, lhs)
}

c_bigfloat_floor <- function(lhs) {
  .Call(`_bignum_c_bigfloat_floor`, lhs)
}

c_bigfloat_trunc <- function(lhs) {
  .Call(`_bignum_c_bigfloat_trunc`, lhs)
}

c_bigfloat_exp <- function(lhs) {
  .Call(`_bignum_c_bigfloat_exp`, lhs)
}

c_bigfloat_expm1 <- function(lhs) {
  .Call(`_bignum_c_bigfloat_expm1`, lhs)
}

c_bigfloat_log <- function(lhs) {
  .Call(`_bignum_c_bigfloat_log`, lhs)
}

c_bigfloat_log10 <- function(lhs) {
  .Call(`_bignum_c_bigfloat_log10`, lhs)
}

c_bigfloat_log2 <- function(lhs) {
  .Call(`_bignum_c_bigfloat_log2`, lhs)
}

c_bigfloat_log1p <- function(lhs) {
  .Call(`_bignum_c_bigfloat_log1p`, lhs)
}

c_bigfloat_cos <- function(lhs) {
  .Call(`_bignum_c_bigfloat_cos`, lhs)
}

c_bigfloat_cosh <- function(lhs) {
  .Call(`_bignum_c_bigfloat_cosh`, lhs)
}

c_bigfloat_sin <- function(lhs) {
  .Call(`_bignum_c_bigfloat_sin`, lhs)
}

c_bigfloat_sinh <- function(lhs) {
  .Call(`_bignum_c_bigfloat_sinh`, lhs)
}

c_bigfloat_tan <- function(lhs) {
  .Call(`_bignum_c_bigfloat_tan`, lhs)
}

c_bigfloat_tanh <- function(lhs) {
  .Call(`_bignum_c_bigfloat_tanh`, lhs)
}

c_bigfloat_acos <- function(lhs) {
  .Call(`_bignum_c_bigfloat_acos`, lhs)
}

c_bigfloat_acosh <- function(lhs) {
  .Call(`_bignum_c_bigfloat_acosh`, lhs)
}

c_bigfloat_asin <- function(lhs) {
  .Call(`_bignum_c_bigfloat_asin`, lhs)
}

c_bigfloat_asinh <- function(lhs) {
  .Call(`_bignum_c_bigfloat_asinh`, lhs)
}

c_bigfloat_atan <- function(lhs) {
  .Call(`_bignum_c_bigfloat_atan`, lhs)
}

c_bigfloat_atanh <- function(lhs) {
  .Call(`_bignum_c_bigfloat_atanh`, lhs)
}

c_bigfloat_gamma <- function(lhs) {
  .Call(`_bignum_c_bigfloat_gamma`, lhs)
}

c_bigfloat_lgamma <- function(lhs) {
  .Call(`_bignum_c_bigfloat_lgamma`, lhs)
}

c_bigfloat_digamma <- function(lhs) {
  .Call(`_bignum_c_bigfloat_digamma`, lhs)
}

c_bigfloat_trigamma <- function(lhs) {
  .Call(`_bignum_c_bigfloat_trigamma`, lhs)
}

c_biginteger <- function(x) {
  .Call(`_bignum_c_biginteger`, x)
}

c_biginteger_to_logical <- function(x) {
  .Call(`_bignum_c_biginteger_to_logical`, x)
}

c_biginteger_to_integer <- function(x) {
  .Call(`_bignum_c_biginteger_to_integer`, x)
}

c_biginteger_to_double <- function(x) {
  .Call(`_bignum_c_biginteger_to_double`, x)
}

c_biginteger_format <- function(x, notation) {
  .Call(`_bignum_c_biginteger_format`, x, notation)
}

c_biginteger_compare <- function(lhs, rhs, na_equal) {
  .Call(`_bignum_c_biginteger_compare`, lhs, rhs, na_equal)
}

c_biginteger_rank <- function(x) {
  .Call(`_bignum_c_biginteger_rank`, x)
}

c_biginteger_add <- function(lhs, rhs) {
  .Call(`_bignum_c_biginteger_add`, lhs, rhs)
}

c_biginteger_subtract <- function(lhs, rhs) {
  .Call(`_bignum_c_biginteger_subtract`, lhs, rhs)
}

c_biginteger_multiply <- function(lhs, rhs) {
  .Call(`_bignum_c_biginteger_multiply`, lhs, rhs)
}

c_biginteger_pow <- function(lhs, rhs) {
  .Call(`_bignum_c_biginteger_pow`, lhs, rhs)
}

c_biginteger_modulo <- function(lhs, rhs) {
  .Call(`_bignum_c_biginteger_modulo`, lhs, rhs)
}

c_biginteger_quotient <- function(lhs, rhs) {
  .Call(`_bignum_c_biginteger_quotient`, lhs, rhs)
}

c_biginteger_sum <- function(x, na_rm) {
  .Call(`_bignum_c_biginteger_sum`, x, na_rm)
}

c_biginteger_prod <- function(x, na_rm) {
  .Call(`_bignum_c_biginteger_prod`, x, na_rm)
}

c_biginteger_cumsum <- function(x) {
  .Call(`_bignum_c_biginteger_cumsum`, x)
}

c_biginteger_cumprod <- function(x) {
  .Call(`_bignum_c_biginteger_cumprod`, x)
}

c_biginteger_cummax <- function(x) {
  .Call(`_bignum_c_biginteger_cummax`, x)
}

c_biginteger_cummin <- function(x) {
  .Call(`_bignum_c_biginteger_cummin`, x)
}

c_biginteger_abs <- function(lhs) {
  .Call(`_bignum_c_biginteger_abs`, lhs)
}

c_biginteger_sign <- function(lhs) {
  .Call(`_bignum_c_biginteger_sign`, lhs)
}
