# Generated by cpp11: do not edit by hand

c_integer_to_bigfloat <- function(x) {
  .Call("_bignum_c_integer_to_bigfloat", x, PACKAGE = "bignum")
}

c_double_to_bigfloat <- function(x) {
  .Call("_bignum_c_double_to_bigfloat", x, PACKAGE = "bignum")
}

c_character_to_bigfloat <- function(x) {
  .Call("_bignum_c_character_to_bigfloat", x, PACKAGE = "bignum")
}

c_bigfloat_to_logical <- function(x) {
  .Call("_bignum_c_bigfloat_to_logical", x, PACKAGE = "bignum")
}

c_bigfloat_to_integer <- function(x) {
  .Call("_bignum_c_bigfloat_to_integer", x, PACKAGE = "bignum")
}

c_bigfloat_to_double <- function(x) {
  .Call("_bignum_c_bigfloat_to_double", x, PACKAGE = "bignum")
}

c_bigfloat_format <- function(x, scientific) {
  .Call("_bignum_c_bigfloat_format", x, scientific, PACKAGE = "bignum")
}

c_bigfloat_compare <- function(lhs, rhs, na_equal) {
  .Call("_bignum_c_bigfloat_compare", lhs, rhs, na_equal, PACKAGE = "bignum")
}

c_bigfloat_rank <- function(x) {
  .Call("_bignum_c_bigfloat_rank", x, PACKAGE = "bignum")
}

c_bigfloat_add <- function(lhs, rhs) {
  .Call("_bignum_c_bigfloat_add", lhs, rhs, PACKAGE = "bignum")
}

c_bigfloat_subtract <- function(lhs, rhs) {
  .Call("_bignum_c_bigfloat_subtract", lhs, rhs, PACKAGE = "bignum")
}

c_bigfloat_multiply <- function(lhs, rhs) {
  .Call("_bignum_c_bigfloat_multiply", lhs, rhs, PACKAGE = "bignum")
}

c_bigfloat_divide <- function(lhs, rhs) {
  .Call("_bignum_c_bigfloat_divide", lhs, rhs, PACKAGE = "bignum")
}

c_bigfloat_pow <- function(lhs, rhs) {
  .Call("_bignum_c_bigfloat_pow", lhs, rhs, PACKAGE = "bignum")
}

c_bigfloat_modulo <- function(lhs, rhs) {
  .Call("_bignum_c_bigfloat_modulo", lhs, rhs, PACKAGE = "bignum")
}

c_bigfloat_sum <- function(x, na_rm) {
  .Call("_bignum_c_bigfloat_sum", x, na_rm, PACKAGE = "bignum")
}

c_bigfloat_prod <- function(x, na_rm) {
  .Call("_bignum_c_bigfloat_prod", x, na_rm, PACKAGE = "bignum")
}

c_bigfloat_cumsum <- function(x) {
  .Call("_bignum_c_bigfloat_cumsum", x, PACKAGE = "bignum")
}

c_bigfloat_cumprod <- function(x) {
  .Call("_bignum_c_bigfloat_cumprod", x, PACKAGE = "bignum")
}

c_bigfloat_cummax <- function(x) {
  .Call("_bignum_c_bigfloat_cummax", x, PACKAGE = "bignum")
}

c_bigfloat_cummin <- function(x) {
  .Call("_bignum_c_bigfloat_cummin", x, PACKAGE = "bignum")
}

c_bigfloat_abs <- function(lhs) {
  .Call("_bignum_c_bigfloat_abs", lhs, PACKAGE = "bignum")
}

c_bigfloat_sign <- function(lhs) {
  .Call("_bignum_c_bigfloat_sign", lhs, PACKAGE = "bignum")
}

c_bigfloat_sqrt <- function(lhs) {
  .Call("_bignum_c_bigfloat_sqrt", lhs, PACKAGE = "bignum")
}

c_bigfloat_ceiling <- function(lhs) {
  .Call("_bignum_c_bigfloat_ceiling", lhs, PACKAGE = "bignum")
}

c_bigfloat_floor <- function(lhs) {
  .Call("_bignum_c_bigfloat_floor", lhs, PACKAGE = "bignum")
}

c_bigfloat_trunc <- function(lhs) {
  .Call("_bignum_c_bigfloat_trunc", lhs, PACKAGE = "bignum")
}

c_bigfloat_exp <- function(lhs) {
  .Call("_bignum_c_bigfloat_exp", lhs, PACKAGE = "bignum")
}

c_bigfloat_expm1 <- function(lhs) {
  .Call("_bignum_c_bigfloat_expm1", lhs, PACKAGE = "bignum")
}

c_bigfloat_log <- function(lhs) {
  .Call("_bignum_c_bigfloat_log", lhs, PACKAGE = "bignum")
}

c_bigfloat_log10 <- function(lhs) {
  .Call("_bignum_c_bigfloat_log10", lhs, PACKAGE = "bignum")
}

c_bigfloat_log2 <- function(lhs) {
  .Call("_bignum_c_bigfloat_log2", lhs, PACKAGE = "bignum")
}

c_bigfloat_log1p <- function(lhs) {
  .Call("_bignum_c_bigfloat_log1p", lhs, PACKAGE = "bignum")
}

c_bigfloat_cos <- function(lhs) {
  .Call("_bignum_c_bigfloat_cos", lhs, PACKAGE = "bignum")
}

c_bigfloat_cosh <- function(lhs) {
  .Call("_bignum_c_bigfloat_cosh", lhs, PACKAGE = "bignum")
}

c_bigfloat_sin <- function(lhs) {
  .Call("_bignum_c_bigfloat_sin", lhs, PACKAGE = "bignum")
}

c_bigfloat_sinh <- function(lhs) {
  .Call("_bignum_c_bigfloat_sinh", lhs, PACKAGE = "bignum")
}

c_bigfloat_tan <- function(lhs) {
  .Call("_bignum_c_bigfloat_tan", lhs, PACKAGE = "bignum")
}

c_bigfloat_tanh <- function(lhs) {
  .Call("_bignum_c_bigfloat_tanh", lhs, PACKAGE = "bignum")
}

c_bigfloat_acos <- function(lhs) {
  .Call("_bignum_c_bigfloat_acos", lhs, PACKAGE = "bignum")
}

c_bigfloat_acosh <- function(lhs) {
  .Call("_bignum_c_bigfloat_acosh", lhs, PACKAGE = "bignum")
}

c_bigfloat_asin <- function(lhs) {
  .Call("_bignum_c_bigfloat_asin", lhs, PACKAGE = "bignum")
}

c_bigfloat_asinh <- function(lhs) {
  .Call("_bignum_c_bigfloat_asinh", lhs, PACKAGE = "bignum")
}

c_bigfloat_atan <- function(lhs) {
  .Call("_bignum_c_bigfloat_atan", lhs, PACKAGE = "bignum")
}

c_bigfloat_atanh <- function(lhs) {
  .Call("_bignum_c_bigfloat_atanh", lhs, PACKAGE = "bignum")
}

c_bigfloat_gamma <- function(lhs) {
  .Call("_bignum_c_bigfloat_gamma", lhs, PACKAGE = "bignum")
}

c_bigfloat_lgamma <- function(lhs) {
  .Call("_bignum_c_bigfloat_lgamma", lhs, PACKAGE = "bignum")
}

c_integer_to_biginteger <- function(x) {
  .Call("_bignum_c_integer_to_biginteger", x, PACKAGE = "bignum")
}

c_double_to_biginteger <- function(x) {
  .Call("_bignum_c_double_to_biginteger", x, PACKAGE = "bignum")
}

c_character_to_biginteger <- function(x) {
  .Call("_bignum_c_character_to_biginteger", x, PACKAGE = "bignum")
}

c_biginteger_to_logical <- function(x) {
  .Call("_bignum_c_biginteger_to_logical", x, PACKAGE = "bignum")
}

c_biginteger_to_integer <- function(x) {
  .Call("_bignum_c_biginteger_to_integer", x, PACKAGE = "bignum")
}

c_biginteger_to_double <- function(x) {
  .Call("_bignum_c_biginteger_to_double", x, PACKAGE = "bignum")
}

c_biginteger_format <- function(x) {
  .Call("_bignum_c_biginteger_format", x, PACKAGE = "bignum")
}

c_biginteger_compare <- function(lhs, rhs, na_equal) {
  .Call("_bignum_c_biginteger_compare", lhs, rhs, na_equal, PACKAGE = "bignum")
}

c_biginteger_rank <- function(x) {
  .Call("_bignum_c_biginteger_rank", x, PACKAGE = "bignum")
}

c_biginteger_add <- function(lhs, rhs) {
  .Call("_bignum_c_biginteger_add", lhs, rhs, PACKAGE = "bignum")
}

c_biginteger_subtract <- function(lhs, rhs) {
  .Call("_bignum_c_biginteger_subtract", lhs, rhs, PACKAGE = "bignum")
}

c_biginteger_multiply <- function(lhs, rhs) {
  .Call("_bignum_c_biginteger_multiply", lhs, rhs, PACKAGE = "bignum")
}

c_biginteger_pow <- function(lhs, rhs) {
  .Call("_bignum_c_biginteger_pow", lhs, rhs, PACKAGE = "bignum")
}

c_biginteger_modulo <- function(lhs, rhs) {
  .Call("_bignum_c_biginteger_modulo", lhs, rhs, PACKAGE = "bignum")
}

c_biginteger_quotient <- function(lhs, rhs) {
  .Call("_bignum_c_biginteger_quotient", lhs, rhs, PACKAGE = "bignum")
}

c_biginteger_sum <- function(x, na_rm) {
  .Call("_bignum_c_biginteger_sum", x, na_rm, PACKAGE = "bignum")
}

c_biginteger_prod <- function(x, na_rm) {
  .Call("_bignum_c_biginteger_prod", x, na_rm, PACKAGE = "bignum")
}

c_biginteger_cumsum <- function(x) {
  .Call("_bignum_c_biginteger_cumsum", x, PACKAGE = "bignum")
}

c_biginteger_cumprod <- function(x) {
  .Call("_bignum_c_biginteger_cumprod", x, PACKAGE = "bignum")
}

c_biginteger_cummax <- function(x) {
  .Call("_bignum_c_biginteger_cummax", x, PACKAGE = "bignum")
}

c_biginteger_cummin <- function(x) {
  .Call("_bignum_c_biginteger_cummin", x, PACKAGE = "bignum")
}

c_biginteger_abs <- function(lhs) {
  .Call("_bignum_c_biginteger_abs", lhs, PACKAGE = "bignum")
}

c_biginteger_sign <- function(lhs) {
  .Call("_bignum_c_biginteger_sign", lhs, PACKAGE = "bignum")
}
